"use client";

import { useState } from "react";
import { generateDocumentSummary } from "@/ai/flows/generate-document-summary";
import ReactMarkdown from "react-markdown";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Loader2,
  Sparkles,
  FileText,
  Download,
  Pencil,
  PlusCircle,
  RefreshCw,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import jsPDF from "jspdf";

type DocInfo = { name: string; type: string; text: string };

type SummaryViewProps = {
  documents: DocInfo[];
  onStartTest: () => void;
  onStartNew: () => void;
};

export function SummaryView({
  documents,
  onStartTest,
  onStartNew,
}: SummaryViewProps) {
  const { toast } = useToast();
  const [summary, setSummary] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [hasGenerated, setHasGenerated] = useState(false);

  const isMultiDoc = documents.length > 1;
  const primaryDoc = documents[0];

  const handleGenerate = async () => {
    if (isLoading) return;

    setIsLoading(true);
    setHasGenerated(true);
    try {
      const result = await generateDocumentSummary({
        documents: documents.map((d) => ({ name: d.name, content: d.text })),
      });
      setSummary(result);
    } catch (error) {
      console.error("Summary generation error:", error);
      const errorMessage = (error as Error)?.message || "An unknown error occurred.";
      const isServiceUnavailable =
        errorMessage.includes("503") ||
        errorMessage.toLowerCase().includes("overloaded");

      toast({
        variant: "destructive",
        title: isServiceUnavailable ? "AI Service Unavailable" : "Error Generating Summary",
        description: isServiceUnavailable
          ? "The AI model is temporarily overloaded. Please try again in a moment."
          : "There was a problem communicating with the AI.",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownload = () => {
    if (!summary) return;

    try {
      const doc = new jsPDF();
      const margin = 20;
      let y = margin;
      const pageWidth = doc.internal.pageSize.getWidth();
      const maxWidth = pageWidth - margin * 2;

      doc.setFontSize(18);
      doc.text(`Study Guide${isMultiDoc ? " (Multi-Document)" : ""}: ${primaryDoc.name}${isMultiDoc ? " +" : ""}`, margin, y);
      y += 12;

      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated by StudyBuddy AI`, margin, y);
      y += 10;

      doc.setTextColor(0, 0, 0);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");

      const lines = summary.split("\n");
      for (const rawLine of lines) {
        if (y > 275) {
          doc.addPage();
          y = margin;
        }

        let line = rawLine.trim();
        if (!line) {
          y += 4;
          continue;
        }

        // Basic markdown → plain text formatting
        if (line.startsWith("### ")) {
          doc.setFont("helvetica", "bold");
          doc.setFontSize(12);
          line = line.slice(4);
        } else if (line.startsWith("## ")) {
          doc.setFont("helvetica", "bold");
          doc.setFontSize(14);
          line = line.slice(3);
        } else if (line.startsWith("# ")) {
          doc.setFont("helvetica", "bold");
          doc.setFontSize(16);
          line = line.slice(2);
        } else if (line.startsWith("- ") || line.startsWith("* ")) {
          line = "\u2022 " + line.slice(2);
        } else if (line.startsWith("> ")) {
          doc.setFont("helvetica", "italic");
          line = line.slice(2);
        } else {
          doc.setFont("helvetica", "normal");
          doc.setFontSize(10);
        }

        line = line
          .replace(/\*\*(.*?)\*\*/g, "$1")
          .replace(/\*(.*?)\*/g, "$1")
          .replace(/`{1,3}[^`]*`{1,3}/g, "")
          .replace(/---+/g, "");

        if (!line) {
          y += 4;
          continue;
        }

        const wrapped = doc.splitTextToSize(line, maxWidth);
        doc.text(wrapped, margin, y);
        y += wrapped.length * 5.5 + 2;
      }

      doc.save(`${primaryDoc.name.replace(/\.[^/.]+$/, "")}-study-guide.pdf`);
    } catch (error) {
      console.error("PDF download error:", error);
      toast({
        variant: "destructive",
        title: "Download Failed",
        description: "Could not generate the PDF. Please try again.",
      });
    }
  };

  const docLabel = isMultiDoc
    ? `${documents.length} documents`
    : primaryDoc.name;

  return (
    <div className="w-full max-w-5xl mx-auto flex-grow flex flex-col space-y-6 animate-in fade-in-50 duration-500">
      <Card>
        <CardHeader>
          <div className="flex flex-col md:flex-row justify-between md:items-center gap-4">
            <div>
              <CardTitle className="text-3xl font-bold font-headline flex items-center gap-2">
                <FileText className="h-7 w-7" />
                {isMultiDoc ? `${documents.length} Documents` : primaryDoc.name}
              </CardTitle>
              <CardDescription>
                AI-generated study guide{isMultiDoc ? " across multiple documents" : ""}, key takeaways, and glossary
              </CardDescription>
            </div>
            <div className="flex gap-2">
              <Button onClick={onStartNew} variant="outline">
                <PlusCircle className="mr-2 h-4 w-4" />
                Start New
              </Button>
              {summary && (
                <Button onClick={handleDownload} variant="outline">
                  <Download className="mr-2 h-4 w-4" />
                  Download
                </Button>
              )}
              <Button onClick={onStartTest} size="lg">
                <Pencil className="mr-2 h-4 w-4" />
                Create Test
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          {!hasGenerated ? (
            <div className="flex flex-col items-center justify-center py-12 text-center space-y-4">
              <FileText className="h-12 w-12 text-muted-foreground" />
              <div className="space-y-1">
                <p className="text-lg font-medium">
                  Generate {isMultiDoc ? "Multi-Document " : ""}Study Guide
                </p>
                <p className="text-sm text-muted-foreground max-w-md">
                  {isMultiDoc
                    ? `Create a comprehensive study guide spanning ${documents.length} documents with chapter breakdowns, key takeaways, glossary, and exam tips.`
                    : "Create a comprehensive study guide with chapter breakdowns, key takeaways, glossary, and exam tips."}
                </p>
              </div>
              <Button onClick={handleGenerate} size="lg" disabled={isLoading}>
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating Study Guide...
                  </>
                ) : (
                  <>
                    <Sparkles className="mr-2 h-4 w-4" />
                    Generate Study Guide
                  </>
                )}
              </Button>
            </div>
          ) : isLoading ? (
            <div className="flex flex-col items-center justify-center py-12 text-center space-y-4">
              <Loader2 className="h-10 w-10 animate-spin text-muted-foreground" />
              <p className="text-sm text-muted-foreground">
                Analyzing document{isMultiDoc ? "s" : ""} and generating study guide...
              </p>
            </div>
          ) : summary ? (
            <>
              <ScrollArea className="max-h-[65vh] pr-4">
                <div className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-semibold prose-h2:mt-8 prose-h2:mb-4 prose-h3:mt-6 prose-h3:mb-3 prose-p:leading-relaxed prose-li:leading-relaxed prose-table:border-collapse prose-th:border prose-th:px-3 prose-th:py-2 prose-td:border prose-td:px-3 prose-td:py-2 prose-code:bg-muted prose-code:px-1 prose-code:py-0.5 prose-code:rounded prose-code:text-sm prose-pre:bg-muted prose-pre:rounded-lg prose-blockquote:border-l-4 prose-blockquote:border-primary prose-blockquote:pl-4 prose-blockquote:text-muted-foreground">
                  <ReactMarkdown>{summary}</ReactMarkdown>
                </div>
              </ScrollArea>
              <div className="flex justify-center gap-4 pt-2">
                <Button
                  onClick={handleGenerate}
                  variant="outline"
                  disabled={isLoading}
                >
                  <RefreshCw className="mr-2 h-4 w-4" />
                  Regenerate
                </Button>
              </div>
            </>
          ) : (
            <div className="flex flex-col items-center justify-center py-12 text-center space-y-4">
              <p className="text-sm text-muted-foreground">
                Something went wrong. Please try again.
              </p>
              <Button onClick={handleGenerate} variant="outline">
                <RefreshCw className="mr-2 h-4 w-4" />
                Try Again
              </Button>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
