"use client";

import { useState } from "react";
import { generateDocumentSummary, type GenerateDocumentSummaryOutput } from "@/ai/flows/generate-document-summary";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Loader2,
  Sparkles,
  FileText,
  ListChecks,
  BookOpen,
  Download,
  Pencil,
  PlusCircle,
  RefreshCw,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import jsPDF from "jspdf";

type SummaryViewProps = {
  documentText: string;
  document: { name: string; type: string };
  onStartTest: () => void;
  onStartNew: () => void;
};

export function SummaryView({
  documentText,
  document,
  onStartTest,
  onStartNew,
}: SummaryViewProps) {
  const { toast } = useToast();
  const [summary, setSummary] = useState<GenerateDocumentSummaryOutput | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [hasGenerated, setHasGenerated] = useState(false);

  const handleGenerate = async () => {
    if (isLoading) return;

    setIsLoading(true);
    setHasGenerated(true);
    try {
      const result = await generateDocumentSummary({
        documentContent: documentText,
      });
      setSummary(result);
    } catch (error) {
      console.error("Summary generation error:", error);
      const errorMessage = (error as Error)?.message || "An unknown error occurred.";
      const isServiceUnavailable =
        errorMessage.includes("503") ||
        errorMessage.toLowerCase().includes("overloaded");

      toast({
        variant: "destructive",
        title: isServiceUnavailable ? "AI Service Unavailable" : "Error Generating Summary",
        description: isServiceUnavailable
          ? "The AI model is temporarily overloaded. Please try again in a moment."
          : "There was a problem communicating with the AI.",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownload = () => {
    if (!summary) return;

    try {
      const doc = new jsPDF();
      const margin = 20;
      let y = margin;
      const pageWidth = doc.internal.pageSize.getWidth();
      const maxWidth = pageWidth - margin * 2;

      doc.setFontSize(18);
      doc.text(`Summary: ${document.name}`, margin, y);
      y += 12;

      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated by StudyBuddy AI`, margin, y);
      y += 8;

      doc.setTextColor(0, 0, 0);

      const writeSection = (title: string, lines: string[]) => {
        if (y > 260) {
          doc.addPage();
          y = margin;
        }
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text(title, margin, y);
        y += 8;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);

        for (const line of lines) {
          const wrappedLines = doc.splitTextToSize(line, maxWidth);
          for (const wrapped of wrappedLines) {
            if (y > 275) {
              doc.addPage();
              y = margin;
            }
            doc.text(wrapped, margin, y);
            y += 6;
          }
        }
        y += 4;
      };

      if (summary.chapterSummaries.length > 0) {
        const chapterLines = summary.chapterSummaries.map(
          (ch) => `${ch.title}: ${ch.summary}`,
        );
        writeSection("Chapter Summaries", chapterLines);
      }

      if (summary.keyTakeaways.length > 0) {
        const takeawayLines = summary.keyTakeaways.map((t) => `- ${t}`);
        writeSection("Key Takeaways", takeawayLines);
      }

      if (summary.glossary.length > 0) {
        const glossaryLines = summary.glossary.map(
          (g) => `${g.term} — ${g.definition}`,
        );
        writeSection("Glossary", glossaryLines);
      }

      doc.save(`${document.name.replace(/\.[^/.]+$/, "")}-summary.pdf`);
    } catch (error) {
      console.error("PDF download error:", error);
      toast({
        variant: "destructive",
        title: "Download Failed",
        description: "Could not generate the PDF. Please try again.",
      });
    }
  };

  const renderSummary = () => {
    if (!summary) return null;

    const { chapterSummaries, keyTakeaways, glossary } = summary;

    return (
      <div className="space-y-6">
        {chapterSummaries.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-xl">
                <BookOpen className="h-5 w-5" />
                Chapter Summaries
              </CardTitle>
              <CardDescription>
                Concise summaries of each section in the document
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Accordion type="multiple" className="space-y-2">
                {chapterSummaries.map((chapter, i) => (
                  <AccordionItem key={i} value={`chapter-${i}`}>
                    <AccordionTrigger className="text-base font-medium">
                      {chapter.title}
                    </AccordionTrigger>
                    <AccordionContent className="text-sm text-muted-foreground">
                      {chapter.summary}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        )}

        {keyTakeaways.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-xl">
                <ListChecks className="h-5 w-5" />
                Key Takeaways
              </CardTitle>
              <CardDescription>
                The most important concepts from the document
              </CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {keyTakeaways.map((takeaway, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm">
                    <Sparkles className="h-4 w-4 mt-0.5 shrink-0 text-primary" />
                    <span>{takeaway}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        )}

        {glossary.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-xl">
                <ListChecks className="h-5 w-5" />
                Glossary
              </CardTitle>
              <CardDescription>
                Key terms and their definitions
              </CardDescription>
            </CardHeader>
            <CardContent>
              <dl className="space-y-3">
                {glossary.map((entry, i) => (
                  <div key={i}>
                    <dt className="font-medium text-sm">{entry.term}</dt>
                    <dd className="text-sm text-muted-foreground mt-0.5">
                      {entry.definition}
                    </dd>
                  </div>
                ))}
              </dl>
            </CardContent>
          </Card>
        )}
      </div>
    );
  };

  return (
    <div className="w-full max-w-5xl mx-auto flex-grow flex flex-col space-y-6 animate-in fade-in-50 duration-500">
      <Card>
        <CardHeader>
          <div className="flex flex-col md:flex-row justify-between md:items-center gap-4">
            <div>
              <CardTitle className="text-3xl font-bold font-headline flex items-center gap-2">
                <FileText className="h-7 w-7" />
                {document.name}
              </CardTitle>
              <CardDescription>
                AI-generated summary, key takeaways, and glossary
              </CardDescription>
            </div>
            <div className="flex gap-2">
              <Button onClick={onStartNew} variant="outline">
                <PlusCircle className="mr-2 h-4 w-4" />
                Start New
              </Button>
              {summary && (
                <Button onClick={handleDownload} variant="outline">
                  <Download className="mr-2 h-4 w-4" />
                  Download
                </Button>
              )}
              <Button onClick={onStartTest} size="lg">
                <Pencil className="mr-2 h-4 w-4" />
                Create Test
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          {!hasGenerated ? (
            <div className="flex flex-col items-center justify-center py-12 text-center space-y-4">
              <BookOpen className="h-12 w-12 text-muted-foreground" />
              <div className="space-y-1">
                <p className="text-lg font-medium">
                  Generate a Document Summary
                </p>
                <p className="text-sm text-muted-foreground max-w-md">
                  Create chapter summaries, key takeaways, and a glossary of
                  important terms from your document.
                </p>
              </div>
              <Button onClick={handleGenerate} size="lg" disabled={isLoading}>
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating Summary...
                  </>
                ) : (
                  <>
                    <Sparkles className="mr-2 h-4 w-4" />
                    Generate Summary
                  </>
                )}
              </Button>
            </div>
          ) : isLoading ? (
            <div className="flex flex-col items-center justify-center py-12 text-center space-y-4">
              <Loader2 className="h-10 w-10 animate-spin text-muted-foreground" />
              <p className="text-sm text-muted-foreground">
                Analyzing document and generating summary...
              </p>
            </div>
          ) : summary ? (
            <>
              {renderSummary()}
              <div className="flex justify-center gap-4 pt-2">
                <Button
                  onClick={handleGenerate}
                  variant="outline"
                  disabled={isLoading}
                >
                  <RefreshCw className="mr-2 h-4 w-4" />
                  Regenerate
                </Button>
              </div>
            </>
          ) : (
            <div className="flex flex-col items-center justify-center py-12 text-center space-y-4">
              <p className="text-sm text-muted-foreground">
                Something went wrong. Please try again.
              </p>
              <Button onClick={handleGenerate} variant="outline">
                <RefreshCw className="mr-2 h-4 w-4" />
                Try Again
              </Button>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
